version: '3.7'

networks:
  postgresql-net:
    name: postgresql-net
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    networks:
      - postgresql-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@matera.com'
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgresql-net